/**
 * cropImages.js — AUTO-GENERATED by scripts/generate-farm-images.js
 * Re-run the script to refresh. Do not edit manually.
 *
 * All images sourced from Wikimedia Commons (CC-BY-SA / Public Domain).
 *
 * Usage:
 *   import { CROP_IMAGES, SOIL_IMAGES, IRRIGATION_IMAGES } from './cropImages';
 *   <Image source={CROP_IMAGES.Tomato} />
 */

// ─── Crop images ─────────────────────────────────────────────────────────────
export const CROP_IMAGES = {
  Tomato: require('../../assets/crops/tomato.jpeg'),
  Onion: require('../../assets/crops/onion.jpeg'),
  Wheat: require('../../assets/crops/wheat.jpeg'),
  Cotton: require('../../assets/crops/cotton.jpeg'),
  Rice: require('../../assets/crops/rice.jpeg'),
  Soybean: require('../../assets/crops/soybean.jpeg'),
  Potato: require('../../assets/crops/potato.jpeg'),
  Maize: require('../../assets/crops/maize.jpeg'),
  Sugarcane: require('../../assets/crops/sugarcane.jpeg'),
  Groundnut: require('../../assets/crops/groundnut.jpeg'),
  Chilli: require('../../assets/crops/chilli.jpeg'),
  Brinjal: require('../../assets/crops/brinjal.jpeg'),
  Okra: require('../../assets/crops/okra.jpeg'),
  Cauliflower: require('../../assets/crops/cauliflower.jpeg'),
  Cabbage: require('../../assets/crops/cabbage.jpeg'),
  Mango: require('../../assets/crops/mango.jpeg'),
  Grape: require('../../assets/crops/grape.jpeg'),
  Pomegranate: require('../../assets/crops/pomegranate.jpeg'),
};

// ─── Soil images ─────────────────────────────────────────────────────────────
export const SOIL_IMAGES = {
  black: require('../../assets/soil/black.jpeg'),
  red: require('../../assets/soil/red.jpeg'),
  alluvial: require('../../assets/soil/alluvial.jpeg'),
  sandy: require('../../assets/soil/sandy.jpeg'),
  clay: require('../../assets/soil/clay.png'),
  laterite: require('../../assets/soil/laterite.jpeg'),
};

// ─── Irrigation images ───────────────────────────────────────────────────────
export const IRRIGATION_IMAGES = {
  drip: require('../../assets/irrigation/drip.jpeg'),
  sprinkler: require('../../assets/irrigation/sprinkler.jpeg'),
  flood: require('../../assets/irrigation/flood.jpeg'),
  rainfed: require('../../assets/irrigation/rainfed.jpeg'),
  canal: require('../../assets/irrigation/canal.jpeg'),
};
