// ─── AGRI STORE MOCK DATA ───────────────────────────────────────────────────

export const CATEGORIES = [
  { id: '1', name: 'Fertilizers', nameHi: 'खाद', icon: 'leaf', color: '#52B788' },
  { id: '2', name: 'Pesticides', nameHi: 'कीटनाशक', icon: 'bug', color: '#E76F51' },
  { id: '3', name: 'Machinery', nameHi: 'मशीनरी', icon: 'construct', color: '#4CC9F0' },
  { id: '4', name: 'Seeds', nameHi: 'बीज', icon: 'flower', color: '#FFB703' },
  { id: '5', name: 'Animal Food', nameHi: 'पशु आहार', icon: 'paw', color: '#F4A261' },
];

export const PRODUCTS = [
  // Fertilizers
  {
    id: 'f1', category: '1',
    name: 'DAP Fertilizer (50 kg)',
    nameHi: 'डीएपी खाद (50 किलो)',
    brand: 'IFFCO',
    price: 1350, mrp: 1500,
    rating: 4.5, reviews: 320,
    image: 'https://via.placeholder.com/200x200/52B788/FFFFFF?text=DAP',
    description: 'Di-Ammonium Phosphate - Best for wheat, rice, and vegetable crops. Boosts root development.',
    inStock: true, unit: 'Bag',
  },
  {
    id: 'f2', category: '1',
    name: 'Urea (50 kg)',
    nameHi: 'यूरिया (50 किलो)',
    brand: 'Chambal Fertilisers',
    price: 266, mrp: 280,
    rating: 4.3, reviews: 580,
    image: 'https://via.placeholder.com/200x200/2D6A4F/FFFFFF?text=Urea',
    description: 'High nitrogen content fertilizer. Ideal for all kharif and rabi crops.',
    inStock: true, unit: 'Bag',
  },
  {
    id: 'f3', category: '1',
    name: 'Potash (MOP) 50kg',
    nameHi: 'पोटाश (50 किलो)',
    brand: 'IPL',
    price: 1100, mrp: 1200,
    rating: 4.2, reviews: 210,
    image: 'https://via.placeholder.com/200x200/1B4332/FFFFFF?text=MOP',
    description: 'Muriate of Potash for improving crop quality and disease resistance.',
    inStock: true, unit: 'Bag',
  },
  // Pesticides
  {
    id: 'p1', category: '2',
    name: 'Chlorpyrifos 20% EC',
    nameHi: 'क्लोरपाइरीफोस',
    brand: 'Dhanuka',
    price: 280, mrp: 320,
    rating: 4.4, reviews: 195,
    image: 'https://via.placeholder.com/200x200/E76F51/FFFFFF?text=Insect',
    description: 'Broad spectrum insecticide for termites, white grubs in soil.',
    inStock: true, unit: 'Litre',
  },
  {
    id: 'p2', category: '2',
    name: 'Mancozeb 75% WP',
    nameHi: 'मैंकोजेब',
    brand: 'Indofil',
    price: 160, mrp: 180,
    rating: 4.1, reviews: 145,
    image: 'https://via.placeholder.com/200x200/F4A261/FFFFFF?text=Fungus',
    description: 'Protective fungicide for blight, leaf spot in tomato, potato.',
    inStock: true, unit: 'Kg',
  },
  // Machinery
  {
    id: 'm1', category: '3',
    name: 'Electric Spray Pump',
    nameHi: 'इलेक्ट्रिक स्प्रेयर',
    brand: 'Aspee',
    price: 4500, mrp: 5200,
    rating: 4.6, reviews: 430,
    image: 'https://via.placeholder.com/200x200/4CC9F0/FFFFFF?text=Pump',
    description: '16L battery-powered knapsack sprayer. 8-hour battery life. Lightweight design.',
    inStock: true, unit: 'Piece',
  },
  {
    id: 'm2', category: '3',
    name: 'Hand Weeder Set',
    nameHi: 'हाथ निराई सेट',
    brand: 'Agripro',
    price: 380, mrp: 450,
    rating: 4.0, reviews: 85,
    image: 'https://via.placeholder.com/200x200/1B4332/FFFFFF?text=Weeder',
    description: 'Set of 5 ergonomic hand tools for weeding and soil loosening.',
    inStock: true, unit: 'Set',
  },
  // Seeds
  {
    id: 's1', category: '4',
    name: 'Hybrid Tomato Seeds',
    nameHi: 'हाइब्रिड टमाटर बीज',
    brand: 'Mahyco',
    price: 120, mrp: 145,
    rating: 4.7, reviews: 560,
    image: 'https://via.placeholder.com/200x200/FFB703/FFFFFF?text=Seeds',
    description: 'High-yield hybrid variety. 90-day crop. Disease resistant.',
    inStock: true, unit: '10g Packet',
  },
  {
    id: 's2', category: '4',
    name: 'Paddy Seeds (IR-36)',
    nameHi: 'धान के बीज (IR-36)',
    brand: 'NSC',
    price: 55, mrp: 65,
    rating: 4.5, reviews: 720,
    image: 'https://via.placeholder.com/200x200/52B788/FFFFFF?text=Paddy',
    description: 'Short duration, high-yielding paddy variety. 105-day crop. Semi-dwarf.',
    inStock: true, unit: 'Kg',
  },
  // Animal Food
  {
    id: 'a1', category: '5',
    name: 'Cattle Feed (50 kg)',
    nameHi: 'पशु आहार (50 किलो)',
    brand: 'Godrej Agrovet',
    price: 1200, mrp: 1350,
    rating: 4.6, reviews: 380,
    image: 'https://via.placeholder.com/200x200/F4A261/FFFFFF?text=Feed',
    description: 'Balanced nutrition for dairy cows. Improves milk yield by up to 15%.',
    inStock: true, unit: 'Bag',
  },
  {
    id: 'a2', category: '5',
    name: 'Poultry Feed (25 kg)',
    nameHi: 'मुर्गी आहार (25 किलो)',
    brand: 'Venkateshwara',
    price: 850, mrp: 950,
    rating: 4.3, reviews: 210,
    image: 'https://via.placeholder.com/200x200/E76F51/FFFFFF?text=Poultry',
    description: 'Complete layer feed for egg-laying hens. High protein formula.',
    inStock: true, unit: 'Bag',
  },
];

// ─── ANIMAL TRADE MOCK DATA ──────────────────────────────────────────────────

export const ANIMAL_LISTINGS = [
  {
    id: 'al1',
    sellerName: 'Ramesh Kumar',
    sellerPhone: '9876543210',
    sellerLocation: 'Nashik, Maharashtra',
    sellerAvatar: 'RK',
    animal: 'Cow',
    animalHi: 'गाय',
    breed: 'Gir',
    age: '4 years',
    gender: 'Female',
    weight: '350 kg',
    milkYield: '12 Litre/Day',
    vaccinated: true,
    price: 55000,
    description: 'Healthy Gir cow, excellent milk producer. Fully vaccinated. Gentle temperament, easy to handle.',
    image: 'https://via.placeholder.com/300x200/52B788/FFFFFF?text=Gir+Cow',
    postedDate: '2 days ago',
    verified: true,
    tags: ['Vaccinated', 'High Milk Yield', 'Healthy'],
  },
  {
    id: 'al2',
    sellerName: 'Suresh Patel',
    sellerPhone: '9123456780',
    sellerLocation: 'Anand, Gujarat',
    sellerAvatar: 'SP',
    animal: 'Buffalo',
    animalHi: 'भैंस',
    breed: 'Murrah',
    age: '5 years',
    gender: 'Female',
    weight: '480 kg',
    milkYield: '16 Litre/Day',
    vaccinated: true,
    price: 75000,
    description: 'Top quality Murrah buffalo. Highest milk fat content. Good for dairy business.',
    image: 'https://via.placeholder.com/300x200/1B4332/FFFFFF?text=Murrah+Buffalo',
    postedDate: '1 day ago',
    verified: true,
    tags: ['High Fat Milk', 'Vaccinated', 'Premium'],
  },
  {
    id: 'al3',
    sellerName: 'Mohan Singh',
    sellerPhone: '8765432109',
    sellerLocation: 'Ludhiana, Punjab',
    sellerAvatar: 'MS',
    animal: 'Goat',
    animalHi: 'बकरी',
    breed: 'Beetal',
    age: '2 years',
    gender: 'Female',
    weight: '35 kg',
    milkYield: '2 Litre/Day',
    vaccinated: false,
    price: 8500,
    description: 'Healthy Beetal goat. Good for milk and meat both. Pair available.',
    image: 'https://via.placeholder.com/300x200/F4A261/FFFFFF?text=Beetal+Goat',
    postedDate: '3 days ago',
    verified: false,
    tags: ['Dual Purpose', 'Healthy'],
  },
  {
    id: 'al4',
    sellerName: 'Dilip Yadav',
    sellerPhone: '7654321098',
    sellerLocation: 'Patna, Bihar',
    sellerAvatar: 'DY',
    animal: 'Bullock',
    animalHi: 'बैल',
    breed: 'Sahiwal',
    age: '6 years',
    gender: 'Male',
    weight: '400 kg',
    milkYield: 'N/A',
    vaccinated: true,
    price: 45000,
    description: 'Strong pair of Sahiwal bullocks, trained for farming. Used 3 seasons. Still strong.',
    image: 'https://via.placeholder.com/300x200/2D6A4F/FFFFFF?text=Sahiwal+Bullock',
    postedDate: '5 days ago',
    verified: true,
    tags: ['Farm Trained', 'Strong', 'Pair Available'],
  },
];

// ─── MACHINERY RENT MOCK DATA ─────────────────────────────────────────────────

export const MACHINERY_LISTINGS = [
  {
    id: 'mr1',
    ownerName: 'Bharat Enterprises',
    ownerPhone: '9900112233',
    location: 'Pune, Maharashtra',
    equipment: 'Tractor (45 HP)',
    equipmentHi: 'ट्रैक्टर (45 HP)',
    brand: 'Mahindra 575',
    pricePerAcre: 600,
    pricePerHour: 500,
    availability: 'Available Now',
    image: 'https://via.placeholder.com/300x180/1B4332/FFFFFF?text=Mahindra+Tractor',
    rating: 4.7, reviews: 125,
    features: ['Ploughing', 'Tilling', 'Sowing', 'Transport'],
    description: 'Well-maintained Mahindra 575 DI tractor with all attachments. Available with driver.',
  },
  {
    id: 'mr2',
    ownerName: 'Kishan Farm Services',
    ownerPhone: '8811223344',
    location: 'Nagpur, Maharashtra',
    equipment: 'Combine Harvester',
    equipmentHi: 'कम्बाइन हार्वेस्टर',
    brand: 'John Deere W70',
    pricePerAcre: 1800,
    pricePerHour: 2500,
    availability: 'Available from Oct 15',
    image: 'https://via.placeholder.com/300x180/F4A261/FFFFFF?text=Harvester',
    rating: 4.8, reviews: 89,
    features: ['Wheat Harvesting', 'Soybean', 'Paddy'],
    description: 'Modern combine harvester. Fast harvesting, minimal grain loss. GPS enabled.',
  },
  {
    id: 'mr3',
    ownerName: 'Agro Solutions',
    ownerPhone: '7722334455',
    location: 'Aurangabad, Maharashtra',
    equipment: 'Rotavator',
    equipmentHi: 'रोटावेटर',
    brand: 'Fieldking FR-200',
    pricePerAcre: 350,
    pricePerHour: 400,
    availability: 'Available Now',
    image: 'https://via.placeholder.com/300x180/52B788/FFFFFF?text=Rotavator',
    rating: 4.5, reviews: 67,
    features: ['Soil Preparation', 'Weed Removal', 'Stubble Management'],
    description: 'Heavy-duty rotavator. Excellent for primary and secondary tillage.',
  },
  {
    id: 'mr4',
    ownerName: 'Kissan Seva Kendra',
    ownerPhone: '6633445566',
    location: 'Solapur, Maharashtra',
    equipment: 'Paddy Transplanter',
    equipmentHi: 'धान रोपाई मशीन',
    brand: 'Kubota NSP-8W',
    pricePerAcre: 900,
    pricePerHour: 1200,
    availability: 'Available Now',
    image: 'https://via.placeholder.com/300x180/4CC9F0/FFFFFF?text=Transplanter',
    rating: 4.3, reviews: 45,
    features: ['8-Row Transplanting', 'GPS Guided', 'Adjustable Spacing'],
    description: 'Self-propelled 8-row paddy transplanter. Saves 70% labour cost vs manual planting.',
  },
];

// ─── LABOUR MOCK DATA ─────────────────────────────────────────────────────────

export const LABOUR_LISTINGS = [
  {
    id: 'lb1',
    type: 'group',
    groupName: 'Shram Shakti Group',
    leader: 'Santosh Mane',
    phone: '9988776655',
    location: 'Nashik, Maharashtra',
    workers: 15,
    skills: ['Harvesting', 'Weeding', 'Planting', 'Spraying'],
    pricePerDay: 400,
    pricePerHour: 60,
    available: true,
    rating: 4.6, reviews: 210,
    image: 'SS',
    description: 'Experienced group of 15 farm workers. Available 7 days a week. Transport arranged.',
  },
  {
    id: 'lb2',
    type: 'individual',
    groupName: null,
    leader: 'Arun Kale',
    phone: '8877665544',
    location: 'Pune, Maharashtra',
    workers: 1,
    skills: ['Tractor Driving', 'Equipment Operation', 'Irrigation'],
    pricePerDay: 600,
    pricePerHour: 80,
    available: true,
    rating: 4.8, reviews: 95,
    image: 'AK',
    description: 'Skilled tractor driver with 10 years experience. Expert in all farming equipment.',
  },
  {
    id: 'lb3',
    type: 'group',
    groupName: 'Mahila Sheti Group',
    leader: 'Savita Pawar',
    phone: '7766554433',
    location: 'Satara, Maharashtra',
    workers: 10,
    skills: ['Paddy Transplanting', 'Grape Harvesting', 'Fruit Picking'],
    pricePerDay: 350,
    pricePerHour: 50,
    available: true,
    rating: 4.7, reviews: 155,
    image: 'MP',
    description: 'Women workers group specializing in delicate crop handling. Paddy transplanting experts.',
  },
  {
    id: 'lb4',
    type: 'individual',
    groupName: null,
    leader: 'Vijay Patil',
    phone: '6655443322',
    location: 'Ahmednagar, Maharashtra',
    workers: 1,
    skills: ['Pesticide Spraying', 'Drip Irrigation', 'Fertigation'],
    pricePerDay: 700,
    pricePerHour: 100,
    available: false,
    rating: 4.9, reviews: 78,
    image: 'VP',
    description: 'Certified pesticide applicator. Expert in drip irrigation installation and fertigation.',
  },
];

// ─── CROP DATA ────────────────────────────────────────────────────────────────

export const CROPS = [
  {
    id: 'c1',
    name: 'Wheat',
    nameHi: 'गेहूं',
    icon: '🌾',
    season: 'Rabi (Winter)',
    sowingMonth: 'October - November',
    harvestMonth: 'March - April',
    duration: '120-150 days',
    waterNeeded: 'Medium (5-6 irrigations)',
    idealTemp: '10-25°C',
    soilType: 'Loamy, Well-drained',
    stages: [
      { name: 'Seed Preparation', nameHi: 'बीज तैयारी', day: 0, duration: 7, tip: 'Select certified seeds. Treat with fungicide before sowing.' },
      { name: 'Sowing', nameHi: 'बुआई', day: 7, duration: 7, tip: 'Sow at 5-6 cm depth. Maintain 22 cm row spacing.' },
      { name: 'Germination', nameHi: 'अंकुरण', day: 14, duration: 10, tip: 'Ensure soil moisture. First irrigation at Crown Root Initiation.' },
      { name: 'Tillering', nameHi: 'कंसे फूटना', day: 30, duration: 25, tip: 'Apply urea top dressing. Remove weeds.' },
      { name: 'Jointing & Booting', nameHi: 'जोड़ लगना', day: 60, duration: 30, tip: 'Second irrigation. Watch for rust disease.' },
      { name: 'Heading & Flowering', nameHi: 'बाली आना', day: 90, duration: 15, tip: 'Critical irrigation period. Avoid water stress.' },
      { name: 'Grain Filling', nameHi: 'दाना भरना', day: 105, duration: 20, tip: 'Last irrigation. Watch for aphids.' },
      { name: 'Maturity & Harvest', nameHi: 'पकाई और कटाई', day: 125, duration: 10, tip: 'Harvest when 90% grains are golden. Use combine harvester.' },
    ],
  },
  {
    id: 'c2',
    name: 'Rice / Paddy',
    nameHi: 'धान / चावल',
    icon: '🌾',
    season: 'Kharif (Monsoon)',
    sowingMonth: 'June - July',
    harvestMonth: 'October - November',
    duration: '105-150 days',
    waterNeeded: 'High (Flooded fields)',
    idealTemp: '22-35°C',
    soilType: 'Clay, Heavy soil',
    stages: [
      { name: 'Nursery Preparation', nameHi: 'नर्सरी तैयारी', day: 0, duration: 25, tip: 'Prepare raised nursery beds. 25 days nursery period.' },
      { name: 'Transplanting', nameHi: 'रोपाई', day: 25, duration: 7, tip: 'Transplant 25-day old seedlings. Maintain 4-5 cm water level.' },
      { name: 'Vegetative Growth', nameHi: 'शाकाहारी विकास', day: 35, duration: 40, tip: 'Apply basal fertilizer. Maintain flooded conditions.' },
      { name: 'Tillering', nameHi: 'कंसे', day: 40, duration: 25, tip: 'Apply nitrogen top dressing. Weed management critical.' },
      { name: 'Panicle Initiation', nameHi: 'बाली शुरू', day: 70, duration: 15, tip: 'Drain field briefly for aeration. Watch for blast disease.' },
      { name: 'Heading & Flowering', nameHi: 'फूल आना', day: 85, duration: 15, tip: 'Maintain water level. Critical pollination period.' },
      { name: 'Grain Filling & Maturity', nameHi: 'दाना पकना', day: 100, duration: 20, tip: 'Drain field 2 weeks before harvest. Check grain moisture.' },
      { name: 'Harvest', nameHi: 'कटाई', day: 120, duration: 7, tip: 'Harvest when 85% grains are golden. Thresh immediately.' },
    ],
  },
  {
    id: 'c3',
    name: 'Tomato',
    nameHi: 'टमाटर',
    icon: '🍅',
    season: 'All Year (Rabi preferred)',
    sowingMonth: 'September - October',
    harvestMonth: 'January - March',
    duration: '90-120 days',
    waterNeeded: 'Medium (Drip irrigation best)',
    idealTemp: '18-27°C',
    soilType: 'Sandy Loam, Well-drained',
    stages: [
      { name: 'Nursery', nameHi: 'नर्सरी', day: 0, duration: 25, tip: 'Sow in raised nursery. Use pro-trays for better results.' },
      { name: 'Transplanting', nameHi: 'रोपाई', day: 25, duration: 5, tip: 'Transplant in evening. Water immediately after transplanting.' },
      { name: 'Vegetative Stage', nameHi: 'पत्ता विकास', day: 30, duration: 20, tip: 'Stake plants when 30cm tall. Apply growth promoters.' },
      { name: 'Flowering', nameHi: 'फूल आना', day: 50, duration: 15, tip: 'Ensure potassium supply. Spray boron for fruit setting.' },
      { name: 'Fruit Setting', nameHi: 'फल लगना', day: 65, duration: 15, tip: 'Spray calcium for blossom-end rot prevention.' },
      { name: 'Fruit Development', nameHi: 'फल विकास', day: 80, duration: 20, tip: 'Watch for leaf curl virus. Maintain consistent irrigation.' },
      { name: 'Harvest', nameHi: 'तुड़ाई', day: 100, duration: 30, tip: 'Start harvesting when fruits turn light pink. Multiple pickings.' },
    ],
  },
  {
    id: 'c4',
    name: 'Soybean',
    nameHi: 'सोयाबीन',
    icon: '🫘',
    season: 'Kharif (Monsoon)',
    sowingMonth: 'June - July',
    harvestMonth: 'September - October',
    duration: '90-100 days',
    waterNeeded: 'Medium',
    idealTemp: '20-30°C',
    soilType: 'Well-drained, Loamy',
    stages: [
      { name: 'Seed Treatment', nameHi: 'बीज उपचार', day: 0, duration: 3, tip: 'Treat seeds with Rhizobium culture for nitrogen fixation.' },
      { name: 'Sowing', nameHi: 'बुआई', day: 3, duration: 5, tip: 'Sow at 45cm x 5cm spacing. Depth 3-4 cm. Soil moisture essential.' },
      { name: 'Emergence', nameHi: 'अंकुरण', day: 8, duration: 10, tip: 'Thin overcrowded plants. First weeding at 20 days.' },
      { name: 'Vegetative Growth', nameHi: 'पत्ता विकास', day: 20, duration: 30, tip: 'Apply phosphorus. Spray insecticide for girdle beetle.' },
      { name: 'Flowering', nameHi: 'फूल', day: 40, duration: 15, tip: 'Avoid water stress. Critical period for pod setting.' },
      { name: 'Pod Development', nameHi: 'फली', day: 55, duration: 25, tip: 'Watch for pod borer. Spray recommended insecticide.' },
      { name: 'Maturity & Harvest', nameHi: 'पकाई', day: 90, duration: 7, tip: 'Harvest when 95% pods turn brown. Harvest early morning.' },
    ],
  },
  {
    id: 'c5',
    name: 'Onion',
    nameHi: 'प्याज',
    icon: '🧅',
    season: 'Rabi (Winter)',
    sowingMonth: 'October - November',
    harvestMonth: 'March - April',
    duration: '130-160 days',
    waterNeeded: 'Medium (Drip preferred)',
    idealTemp: '13-24°C',
    soilType: 'Sandy Loam, Rich in Sulfur',
    stages: [
      { name: 'Nursery', nameHi: 'नर्सरी', day: 0, duration: 40, tip: 'Sow densely in raised beds. 40-day nursery period.' },
      { name: 'Field Preparation & Transplanting', nameHi: 'रोपाई', day: 40, duration: 7, tip: 'Transplant at 10x10 cm spacing. Avoid deep planting.' },
      { name: 'Vegetative Growth', nameHi: 'पत्ता विकास', day: 50, duration: 40, tip: 'Weed twice. Apply nitrogen for leaf growth.' },
      { name: 'Bulb Formation', nameHi: 'प्याज बनना', day: 90, duration: 40, tip: 'Stop nitrogen. Apply potash and phosphorus for bulb quality.' },
      { name: 'Maturity', nameHi: 'पकाई', day: 130, duration: 15, tip: 'Reduce irrigation 15 days before harvest. Tops will fall.' },
      { name: 'Harvest & Curing', nameHi: 'खुदाई', day: 145, duration: 10, tip: 'Harvest when 50% tops fall. Cure in shade for 7-10 days.' },
    ],
  },
];

// ─── WEATHER FORECAST MOCK DATA ───────────────────────────────────────────────

export const WEATHER_MOCK = {
  city: 'Nashik',
  state: 'Maharashtra',
  current: {
    temp: 28,
    feelsLike: 31,
    humidity: 65,
    windSpeed: 12,
    windDir: 'SW',
    condition: 'Partly Cloudy',
    icon: 'partly-sunny',
    uvIndex: 6,
    visibility: 8,
    pressure: 1012,
    rainChance: 30,
  },
  hourly: [
    { time: '6 AM', temp: 22, icon: 'sunny', rain: 0 },
    { time: '9 AM', temp: 26, icon: 'partly-sunny', rain: 5 },
    { time: '12 PM', temp: 31, icon: 'partly-sunny', rain: 20 },
    { time: '3 PM', temp: 33, icon: 'cloud', rain: 40 },
    { time: '6 PM', temp: 29, icon: 'rainy', rain: 70 },
    { time: '9 PM', temp: 25, icon: 'rainy', rain: 60 },
  ],
  weekly: [
    { day: 'Mon', high: 33, low: 22, icon: 'partly-sunny', rain: 20 },
    { day: 'Tue', high: 31, low: 21, icon: 'rainy', rain: 70 },
    { day: 'Wed', high: 28, low: 20, icon: 'rainy', rain: 80 },
    { day: 'Thu', high: 30, low: 21, icon: 'partly-sunny', rain: 30 },
    { day: 'Fri', high: 34, low: 23, icon: 'sunny', rain: 10 },
    { day: 'Sat', high: 35, low: 24, icon: 'sunny', rain: 5 },
    { day: 'Sun', high: 33, low: 22, icon: 'partly-sunny', rain: 15 },
  ],
  alerts: [
    {
      type: 'warning',
      title: 'Rain Alert',
      message: 'Heavy rain expected Tuesday-Wednesday. Delay pesticide spraying.',
      icon: 'rainy',
    },
  ],
  farmingTip: 'Good time to apply basal fertilizer. Irrigate fields before expected rain.',
};

// ─── CHAT MESSAGES MOCK ───────────────────────────────────────────────────────

export const MOCK_MESSAGES = [
  {
    id: 'm1',
    senderId: 'other',
    senderName: 'Ramesh Kumar',
    text: 'Namaskar! Aapko meri Gir gaay mein interest hai?',
    time: '10:30 AM',
    date: 'Today',
  },
  {
    id: 'm2',
    senderId: 'me',
    text: 'Haan, kya gaay ki health theek hai? Milk yield kaisi hai?',
    time: '10:32 AM',
    date: 'Today',
  },
  {
    id: 'm3',
    senderId: 'other',
    senderName: 'Ramesh Kumar',
    text: 'Bilkul theek hai. Daily 12 litre milk deti hai. Doctor certificate bhi hai.',
    time: '10:35 AM',
    date: 'Today',
  },
];

// ─── COMMUNITY POSTS MOCK DATA ────────────────────────────────────────────────

export const POST_CATEGORIES = [
  { id: 'all',     label: 'All',           icon: 'apps',             color: '#1B4332' },
  { id: 'problem', label: 'Crop Problem',  icon: 'bug',              color: '#E63946' },
  { id: 'tip',     label: 'Farming Tips',  icon: 'bulb',             color: '#FFB703' },
  { id: 'market',  label: 'Market Price',  icon: 'trending-up',      color: '#4CC9F0' },
  { id: 'success', label: 'Success Story', icon: 'ribbon',           color: '#52B788' },
  { id: 'weather', label: 'Weather Talk',  icon: 'partly-sunny',     color: '#F4A261' },
  { id: 'general', label: 'General',       icon: 'chatbubbles',      color: '#7F9B87' },
];

export const COMMUNITY_POSTS = [
  {
    id: 'post1',
    authorName: 'Ramesh Patil',
    authorAvatar: 'RP',
    authorLocation: 'Nashik, Maharashtra',
    authorCrop: 'Tomato, Onion',
    category: 'problem',
    title: 'Tomato leaves turning yellow from bottom – urgent help!',
    description: 'My tomato plants are 45 days old. Leaves are turning yellow from the bottom and spreading up. Some plants are wilting too. Soil is black cotton. What disease is this and what spray should I use?',
    image: null,
    likes: 38,
    comments: 12,
    liked: false,
    bookmarked: false,
    timeAgo: '2 hours ago',
    tags: ['Tomato', 'Yellow Leaves', 'Disease'],
    verified: false,
  },
  {
    id: 'post2',
    authorName: 'Dr. Suresh KVK',
    authorAvatar: 'SK',
    authorLocation: 'Pune KVK, Maharashtra',
    authorCrop: 'Agriculture Expert',
    category: 'tip',
    title: 'Best time to apply DAP fertilizer for wheat – must read!',
    description: 'Farmers, apply DAP only as basal dose at time of sowing. Many farmers apply it as top dressing which is wasteful. DAP must be mixed in soil for roots to absorb phosphorus properly. Top dressing with Urea is correct after 21 days.',
    image: null,
    likes: 124,
    comments: 34,
    liked: true,
    bookmarked: true,
    timeAgo: '5 hours ago',
    tags: ['Wheat', 'DAP', 'Fertilizer Tip'],
    verified: true,
  },
  {
    id: 'post3',
    authorName: 'Mohan Yadav',
    authorAvatar: 'MY',
    authorLocation: 'Indore, MP',
    authorCrop: 'Soybean, Wheat',
    category: 'market',
    title: 'Soybean price update – Indore mandi today ₹4,850/quintal',
    description: 'Today at Indore mandi: Soybean ₹4,850/quintal. Last week it was ₹4,600. Experts say prices may go up to ₹5,200 by December due to low production this kharif. Hold stock if you can wait 3-4 weeks.',
    image: null,
    likes: 89,
    comments: 45,
    liked: false,
    bookmarked: false,
    timeAgo: '8 hours ago',
    tags: ['Soybean', 'Mandi Price', 'Market Update'],
    verified: false,
  },
  {
    id: 'post4',
    authorName: 'Savita Devi',
    authorAvatar: 'SD',
    authorLocation: 'Varanasi, UP',
    authorCrop: 'Rice, Vegetable',
    category: 'success',
    title: 'Started drip irrigation – saved 60% water and doubled income!',
    description: 'Two years ago I took government subsidy for drip irrigation on my 2 acre field. Before, I used to flood irrigate and water bill was ₹8,000/month. Now with drip, it is only ₹3,000. Also my vegetable yield doubled because plants get water exactly when needed. Other farmers should try this!',
    image: null,
    likes: 215,
    comments: 67,
    liked: true,
    bookmarked: false,
    timeAgo: '1 day ago',
    tags: ['Drip Irrigation', 'Success Story', 'Water Saving'],
    verified: false,
  },
  {
    id: 'post5',
    authorName: 'Bharat Singh',
    authorAvatar: 'BS',
    authorLocation: 'Amritsar, Punjab',
    authorCrop: 'Wheat, Paddy',
    category: 'problem',
    title: 'White powder on wheat leaves – is this powdery mildew?',
    description: 'White powder like coating on wheat leaves. Started on lower leaves, now spreading to upper leaves also. Temperature here is around 18-22°C with morning fog. Is this powdery mildew? Which fungicide should I use and how many times?',
    image: null,
    likes: 19,
    comments: 9,
    liked: false,
    bookmarked: false,
    timeAgo: '1 day ago',
    tags: ['Wheat', 'Powdery Mildew', 'Fungal Disease'],
    verified: false,
  },
  {
    id: 'post6',
    authorName: 'Agri Expert - KVK',
    authorAvatar: 'AE',
    authorLocation: 'Coimbatore, Tamil Nadu',
    authorCrop: 'Agriculture Scientist',
    category: 'tip',
    title: 'How to do soil testing at home before spending on fertilizers',
    description: 'Before buying fertilizers, always do soil test. You can get soil testing kit from nearest KVK (Krishi Vigyan Kendra) for just ₹5-10. Or take soil sample to agriculture department lab free of cost. This will tell exact nutrient deficiency and save you ₹3,000-5,000 per acre on unnecessary fertilizers.',
    image: null,
    likes: 342,
    comments: 89,
    liked: false,
    bookmarked: true,
    timeAgo: '2 days ago',
    tags: ['Soil Testing', 'Money Saving', 'Expert Advice'],
    verified: true,
  },
];

export const COMMUNITY_COMMENTS = {
  post1: [
    { id: 'c1', authorName: 'Vijay Patil', authorAvatar: 'VP', text: 'This looks like Early Blight (Alternaria). Spray Mancozeb 75% WP at 2.5g per litre water. Repeat after 10 days.', timeAgo: '1 hour ago', likes: 15 },
    { id: 'c2', authorName: 'Dr. KVK Expert', authorAvatar: 'DE', text: 'Also check for Fusarium wilt if plants are dying completely. Pull out affected plants and destroy them immediately before it spreads.', timeAgo: '45 min ago', likes: 22 },
    { id: 'c3', authorName: 'Santosh Mane', authorAvatar: 'SM', text: 'Same problem I had last year. Copper oxychloride spray worked very well for me. 3 sprays every 10 days.', timeAgo: '30 min ago', likes: 8 },
  ],
  post2: [
    { id: 'c4', authorName: 'Dinesh Kumar', authorAvatar: 'DK', text: 'Thank you sir! I was applying DAP as top dressing for 5 years. Now I understand my mistake. Will change this season.', timeAgo: '4 hours ago', likes: 31 },
    { id: 'c5', authorName: 'Meena Devi', authorAvatar: 'MD', text: 'What about MOP? Should it also be given at basal only?', timeAgo: '3 hours ago', likes: 7 },
  ],
};

// ─── USER PROFILE MOCK DATA ──────────────────────────────────────────────────

export const USER_PROFILE = {
  id: 'user1',
  name: 'Shubham Yeljale',
  phone: '+91 98765 43210',
  village: 'Shirdi',
  district: 'Ahmednagar',
  state: 'Maharashtra',
  pincode: '423414',
  avatar: 'SY',
  memberSince: 'January 2024',
  verified: true,
  farm: {
    totalLand: '4.5 acres',
    landType: 'Black Cotton Soil',
    irrigationType: 'Drip + Borewell',
    mainCrops: ['Tomato', 'Onion', 'Wheat'],
    animals: ['2 Cows', '1 Buffalo'],
    village: 'Shirdi, Ahmednagar',
  },
  stats: {
    posts: 12,
    questions: 8,
    helpful: 34,
    listings: 3,
  },
  myPosts: ['post4'],
  savedPosts: ['post2', 'post6'],
};
